let name="sanika";
let age=20;
let height=5.6;
let rollnumber=4;
const car="bmw";
const bike="fz";
const mobilenumber="true";
console.log(name);
console.log(age);
console.log(height);
console.log(rollnumber);
console.log(car);
console.log(bike);
console.log(mobilenumber);
let str="hello world";
let num=123;
let bool=true;
let sym= Symbol("sanika ugale");
let undef=undefined;
let nul=null;
console.log(Number);
console.log(Boolean);
console.log(sym);
console.log(undefined);
console.log(null);